/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.com.interfaces;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import mx.com.conversor.conversor_moneda;

/**
 *
 * @author La inge
 */
public class Moneda extends javax.swing.JFrame {

    /**
     * Creates new form Moneda
     */
    public Moneda() {
        initComponents();

        A.setEnabled(false);
        int width = 330; // Establece el ancho deseado en píxeles
        int height = 240; // Establece el alto deseado en píxeles
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        setSize(width, height);
        int x = (screenSize.width - width) / 2;
        int y = (screenSize.height - height) / 2;
        setLocation(x, y);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DE = new javax.swing.JComboBox<>();
        A = new javax.swing.JComboBox<>();
        monto = new javax.swing.JTextField();
        convertido = new java.awt.Label();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        DE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXN", "USD", "EUR", "GBP", "JPY", "KRW" }));
        DE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DEActionPerformed(evt);
            }
        });
        getContentPane().add(DE);
        DE.setBounds(20, 20, 108, 22);

        getContentPane().add(A);
        A.setBounds(20, 100, 108, 22);

        monto.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        getContentPane().add(monto);
        monto.setBounds(20, 60, 108, 26);

        convertido.setBackground(new java.awt.Color(255, 255, 255));
        convertido.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        getContentPane().add(convertido);
        convertido.setBounds(20, 140, 108, 22);

        jButton2.setText("Convertir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(190, 150, 90, 30);

        jButton3.setText("<-");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(260, 0, 50, 23);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGEN/descarga (2).jpg"))); // NOI18N
        getContentPane().add(jButton1);
        jButton1.setBounds(0, 0, 312, 200);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DEActionPerformed

        String monedaConvertir = (String) DE.getSelectedItem();
        String[] opciones = {"MXN", "USD", "GBP", "EUR", "JPY", "KRW"};
        A.setEnabled(false);
        convertido.setText(" ");
        for (int j = 0; j < opciones.length; j++) {

            A.removeAllItems();

        }
        for (int i = 0; i < opciones.length; i++) {
            if (monedaConvertir != opciones[i]) {
                A.addItem(opciones[i]);
            }
        }
        A.setEnabled(true);


    }//GEN-LAST:event_DEActionPerformed

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char c = evt.getKeyChar();

        String text = monto.getText();

        if (!((c >= '0' && c <= '9') || c == '.' || c == KeyEvent.VK_BACK_SPACE)) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "No puede digitar letras ni caracteres especiales");
        }

        if (c == '.' && text.contains(".")) {
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, "Ya se ha ingresado un punto decimal");
        }
    }//GEN-LAST:event_montoKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String monedaConvertir = (String) DE.getSelectedItem();
        String monedaConvertida = (String) A.getSelectedItem();
        String convertir = monto.getText();
        double convertirAuxiliar = Double.parseDouble(convertir);
        if (monedaConvertir.equals("MXN")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.PesoConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        } else if (monedaConvertir.equals("USD")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.dolarConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        } else if (monedaConvertir.equals("EUR")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.euroConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        } else if (monedaConvertir.equals("GBP")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.libraConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        } else if (monedaConvertir.equals("JPY")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.yenConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        } else if (monedaConvertir.equals("KRW")) {
            conversor_moneda monto = new conversor_moneda();

            double convertidor = monto.wonConvertir(convertirAuxiliar, monedaConvertida);
            convertido.setText(convertidor + " " + monedaConvertida);
        }             // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        principal prin = new principal();
        prin.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Moneda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Moneda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> A;
    private javax.swing.JComboBox<String> DE;
    private java.awt.Label convertido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
